# Generated by Django 5.2.1 on 2025-05-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentScheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=15)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('api_endpoint_member', models.URLField(null=True)),
                ('api_endpoint_contribution', models.URLField(null=True)),
                ('tel_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAPI',
            fields=[
                ('Id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('fund_type', models.CharField(choices=[('pension', 'Pension Fund'), ('provident', 'Provident Fund'), ('gratuity', 'Gratuity Fund'), ('savings', 'Savings Fund')], max_length=50)),
                ('contributions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('exited_date', models.DateField(blank=True, null=True)),
                ('exited_flag', models.BooleanField(default=False)),
                ('estimated_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('subscription_date', models.DateField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('last_withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('investment_scheme', models.ManyToManyField(related_name='staff_api', to='database.investmentscheme')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_api', to='database.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retro_employee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retro_employer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('contribution_date', models.DateField()),
                ('approved_contribution', models.BooleanField(default=False)),
                ('total_contribution', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('investment_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.investmentscheme')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='database.staffapi')),
            ],
        ),
        migrations.AddField(
            model_name='investmentscheme',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.tenant'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('estimated_profit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='database.investmentscheme')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='database.staffapi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='database.tenant')),
            ],
            options={
                'unique_together': {('staff', 'scheme')},
            },
        ),
    ]
